### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by astoilkov** [Oktavilla/markdown-it-table-of-contents#14]
Our application uses `markdown-it-table-of-contents` and we are getting error reports from users with the following error. Unfortunately, I can't seem to find a way to replicate it. Maybe the author of this extension could have better idea of why this error could be thrown.

We are using version 0.2.2. We could update but I didn't seen any fix regarding something similar to this in the commits history.

```
{
  "message": "Cannot read property 'type' of undefined",
  "os": "Linux 4.8",
  "path": "node_modules/markdown-it-table-of-contents/index.js",
  "code": "(state.tokens.slice(-1)[0].type === \"softbreak\") ",
  "line": 24,
  "column": 36,
  "stack": [
    "at Array.toc (node_modules/markdown-it-table-of-contents/index.js:24:36)",
    "at ParserInline.tokenize (node_modules/markdown-it/lib/parser_inline.js:135:22)",
    "at ParserInline.parse (node_modules/markdown-it/lib/parser_inline.js:163:8)",
    "at Array.inline (node_modules/markdown-it/lib/rules_core/inline.js:10:23)",
    "at Core.process (node_modules/markdown-it/lib/parser_core.js:51:13)",
    "at MarkdownIt.parse (node_modules/markdown-it/lib/index.js:519:13)",
    "at MarkdownIt.render (node_modules/markdown-it/lib/index.js:539:36)"
  ]
}
```

**Comment by martinlissmyr** [comment]
Should be fixed in 0.3.1
